# Uses secrets:
#   DOCKER_USERNAME
#   DOCKER_PASSWORD

name: Workflow Call - Docker Push

on:
  workflow_call:

jobs:
  push:
    name: Docker Push (${{ github.repository }}:latest)
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Load image
        run: docker load --input /tmp/image.tar

      - name: Docker login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Docker push
        run: docker push ${{ github.repository }}:latest
